image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo 'PATH_add /home/gitpod/julia-1.8.2/bin' > /workspace/.envrc \
          && echo 'PATH_add ~/julia-1.8.2/bin' > /workspace/.envrc \
          && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc \
          && direnv allow /workspace \
          && cp /workspace/.envrc /home/gitpod \
          && direnv allow /home/gitpod

  - command:  julia --startup-file=no --depwarn=no /workspace/.vscode-remote/extensions/geniebuilder.geniebuilder-insider-0.3.1-universal/scripts/updategb.jl \
              && cd /home/gitpod/.julia/geniebuilder/apps \
              && git clone https://github.com/michaelfliegner/GenieBuildLifeProto
          
  - command: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate();include("testsCreateContract.jl")'
ports:
  - name: postgres
    description: data base server
    port: 5432
    visibility: private
    onOpen: ignore


