
image: michaelfliegner/gitpodpgijulia
tasks:
  - command: julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); include("run.jl")' 

ports:
  - name: postgres
    description: data base server
    port: 5432
    visibility: private
    onOpen: ignore

  - name: Web App
    description: The main application web server
    port: 8000
    visibility: public
    onOpen: open-browser
vscode:
  extensions:
    - pinage404.markdown-extension-pack